#!/usr/bin/env ruby

# requires jmeter to be installed beforehand
# Settings
# TEST_DOMAIN
# TEST_PORT
# TEST_AUTH_TOKEN

require 'bundler/setup'
require 'ruby-jmeter'
require 'faker'

test do
  defaults domain: ENV['TEST_DOMAIN'], port: ENV['TEST_PORT']

  cache clear_each_iteration: true

  cookies

  auth url: "/tokens/#{ENV['TEST_AUTH_TOKEN']}"

  threads 50, {ramp_time: 60, duration: 120, continue_forever: true} do

    random_timer 1000, 3000

    extract name: 'authenticity_token',
            regex: 'meta content="(.+?)" name="csrf-token"'

    # transaction '01_homepage_view' do
    #   visit '/' do
    #     assert contains: 'Enter your MOJ email address'
    #   end
    # end

    transaction '01_auth_token_login' do
      visit "/tokens/#{ENV['AUTH_TOKEN']}" do
        assert contains: 'Welcome to People Finder'
      end
    end

    transaction '02_create_a_new_person' do
      first_name = Faker::Name.first_name
      last_name = Faker::Name.last_name
      full_name = "#{first_name} #{last_name}"
      submit '/people', {
                              fill_in: {
                                  'utf8'                => '%E2%9C%93',
                                  'authenticity_token'  => '${authenticity_token}',
                                  'person[given_name]'   =>  first_name,
                                  'person[password]'     =>  last_name,
                                  'person[email]'        => "#{Faker::Internet.user_name}@digital.justice.gov.uk",
                                  'commit'              => 'Save',
                              }
                           } do
        assert contains: "Created #{full_name}’s profile"
      end

    end
  end
end.run